kafkaPool: nav-dev
environment: dev
replicas_min: 1
replicas_max: 2
cpu: 200m
memory: 400Mi
db_tier: db-f1-micro
env:
  SPRING_PROFILES_ACTIVE: default,testdatareset
  DITT_SYKEFRAVAER_FRONTEND_CLIENT_ID: dev-gcp:flex:ditt-sykefravaer
  DITT_SYKEFRAVAER_FRONTEND_TOKENX_IDP: https://oidc-ver2.difi.no/idporten-oidc-provider/
  AIVEN_KAFKA_AUTO_OFFSET_RESET: earliest
