kafkaPool: nav-prod
environment: prod
replicas_min: 2
replicas_max: 3
cpu: 400m
memory: 600Mi
db_tier: db-custom-1-3840
db_highAvailability: true
db_pointInTimeRecovery: true
env:
  SPRING_PROFILES_ACTIVE: default
  DITT_SYKEFRAVAER_FRONTEND_CLIENT_ID: prod-gcp:flex:ditt-sykefravaer
