CREATE TABLE INNTEKTSMELDING
(
    ID                 VARCHAR(36) DEFAULT UUID_GENERATE_V4() PRIMARY KEY,
    FNR                VARCHAR(11)              NOT NULL,
    INNTEKTSMELDING_ID VARCHAR(36) UNIQUE,
    ARBEIDSGIVERTYPE   VARCHAR,
    INNTEKTSMELDING    TEXT,
    OPPRETTET          TIMESTAMP WITH TIME ZONE NOT NULL,
    MOTTATT_DATO       TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX INNTEKTSMELDING_FNR_IDX ON INNTEKTSMELDING (FNR);
