name: "Deploy topic"
on:
  push:
    paths:
      - nais/topics/**
      - .github/workflows/topic.yml
jobs:
  deploy-topic-to-dev:
    if: github.ref_name == 'main' || startsWith(github.ref_name, 'dev-')
    name: Deploy topic to dev-gcp
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy ditt-sykefravaer-melding topic to dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/topics/ditt-sykefravaer-melding.yaml
          VARS: nais/topics/dev.json

  deploy-topic-to-prod:
    if: github.ref_name == 'main'
    name: Deploy topic to prod-gcp
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy ditt-sykefravaer-melding topic to prod-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/topics/ditt-sykefravaer-melding.yaml
          VARS: nais/topics/prod.json
